version: '3.8'

services:
  wordpress:
    image: ghcr.io/[ORG]/[PACKAGE]:latest
    restart: always
    environment:
      # Database Configuration
      WORDPRESS_DB_HOST: [DB_HOST]
      WORDPRESS_DB_USER: [DB_USER]
      WORDPRESS_DB_PASSWORD: [DB_PWD]
      WORDPRESS_DB_NAME: [DB_NAME]
      WORDPRESS_DB_CHARSET: utf8
      WORDPRESS_DB_COLLATE: ""
      WORDPRESS_TABLE_PREFIX: wp_
      
      # Security Keys and Salts
      WORDPRESS_AUTH_KEY: "xK9vN2mR8wP5qL7hT4jF6nB3sY1cW0eZ8dG5uV4bX2aQ6mK9pL3fR7wT1hN5sC4j"
      WORDPRESS_SECURE_AUTH_KEY: "bD8mW3nK7pQ2rY5fL9vH6xT1sN4jC8gB2eZ6uA3kM7qR5wP9tL4hV8nG1xS2dF6y"
      WORDPRESS_LOGGED_IN_KEY: "yT7rP4mL2nK9vH5xB8cW6fG3sQ1dZ4eN7uJ2kA6pM5qR8wL3tV9hX4nC7gY2jS5b"
      WORDPRESS_NONCE_KEY: "vL6pW9nM2rK8tH4xQ5yF3sC7dG1eB6uN2aJ4kZ8qP3mR7wV5hL9xT2nK6cY4jG8f"
      WORDPRESS_AUTH_SALT: "hQ3fB7nW5mK8rY2tL6vP9xC4sG1dN8eA6uJ3kZ5qH7wM2pR4nL8vT9xB6yK3jF2c"
      WORDPRESS_SECURE_AUTH_SALT: "sK5dN8mW3rP6tL9vY2xH4fQ7gC1eB8uZ6aJ2kM4qV7wR9pN3hL5xT8nG2yF6jC4k"
      WORDPRESS_LOGGED_IN_SALT: "cY9pT6mR2nL8vK4xH7fW5qB3sG1dQ8eN6uA2kJ4pM9rZ3wV7hL5xT2nC8yK6jG4b"
      WORDPRESS_NONCE_SALT: "fR4wK7pL9nM2vH6xQ3tY8sB5cG1dN4eZ6uJ8kA2qP7mW3rV9hL5xT4nK2yF6jC8g"
      
      # Redis Configuration
      REDIS_URL: redis
      REDIS_PASSWORD: ""
      
      # Environment Settings
      WP_ENVIRONMENT_TYPE: production
      WORDPRESS_DEBUG: 0
      WORDPRESS_DEBUG_LOG: 1
      WORDPRESS_DEBUG_DISPLAY: 0
      
      # WordPress Features
      WORDPRESS_ALLOW_MULTISITE: 0
      
      # Third-Party
      WP_SENTRY_BROWSER_DSN: "[OPTIONAL_SENTRY_BROWSER_DSN]"
      WP_SENTRY_PHP_DSN: "[OPTIONAL_SENTRY_PHP_DSN]"
      JWT_AUTH_SECRET_KEY: "[OPTIONAL_JWT_SECRET_KEY]"
      
    networks:
      - web_gateway
      - internal

    # --- ZERO DOWNTIME CONFIGURATION ---
    deploy:
      update_config:
        order: start-first    # Spin up new version before killing the old one
        failure_action: rollback
        delay: 10s            # Wait between container swaps
      resources:
        limits:
          memory: 1024M

    healthcheck:
      # Verifies WP is actually serving pages before Traefik routes traffic
      test: ["CMD", "curl", "-f", "http://localhost/wp-login.php"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

    labels:
    # Assumes a Traefik setup
      - "traefik.enable=true"
      - "traefik.docker.network=web_gateway"
      - "traefik.http.routers.[DOMAIN]].rule=Host(`[DOMAIN]].co.uk`) || Host(`www.[DOMAIN]].co.uk`)"
      - "traefik.http.routers.[DOMAIN]].entrypoints=websecure"
      - "traefik.http.routers.[DOMAIN]].tls=true"
      - "traefik.http.routers.[DOMAIN]].tls.certresolver=letsencrypt"
      - "traefik.http.services.[DOMAIN]].loadbalancer.server.port=80"
      
      # Assumes an Ofelia setup
      - "ofelia.enabled=true"
      - "ofelia.job-exec.wp-cron.schedule=@every 5m"
      - "ofelia.job-exec.wp-cron.command=wp cron event run --due-now"
      - "ofelia.job-exec.wp-cron.user=www-data"

  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal

networks:
  web_gateway:
    external: true
  internal:
    driver: bridge