#!/bin/bash -e
 
clear

echo "================================================================="
echo "Awesome UFM WordPress Installer!!"
echo "================================================================="

#Get system username and set root url
#echo "System User (ufm01): "
#read -e sysusr

sysusr=$USER

if [ "$sysusr" == "ufm01" ]
then
rooturl=ufmedia.net
dbusr="db_ufm"
fi

# parse the current directory name and set and create db name
echo "Creating database..."
currentdirectory=${PWD##*/}
dbradix="01_dev"
userradix="_admin"
dbname="$currentdirectory$dbradix"
wpuser="$currentdirectory$userradix"

sudo /usr/local/psa/bin/database --create $dbname -domain $rooturl -print-id -server localhost -type mysql

#Set the site name
echo "Site Name: "
read -e sitename

echo "Add Pages (CSV no spaces): "
read -e allpages

echo "Add CPTs (CSV no spaces): "
read -e allCPTs

echo "Install WooCommerce? (y/n)"
read -e woo

echo "Run Install? (y/n)"
read -e run

# if the user didn't say no, then go ahead an install
if [ "$run" == n ] ; then
exit
else

# download the WordPress core files
echo "Downloading WordPress core..."
wp core download

# create the wp-config file
echo "Creating WordPress config file..."
wp core config --dbname=$dbname --dbuser=$dbusr --dbpass=ceVh5~27


# create database, and install WordPress
echo "Building database and installing..."
#wp db create
wp core install --url="http://dev.$rooturl/$currentdirectory" --title="$sitename" --admin_user="$wpuser" --admin_password="jt00" --admin_email="admin@ufmedia.co.uk"

# delete akismet and hello dolly
echo "Removing plugins..."
wp plugin delete akismet
wp plugin delete hello
echo "Installing plugins..."
wp plugin install wordpress-seo --activate
wp plugin install https://www.ufmservices.net/plugins/gf.zip --activate
wp plugin install https://www.ufmservices.net/plugins/acfpro.zip --activate
wp plugin install https://www.ufmservices.net/plugins/acfimage.zip --activate
wp plugin install https://www.ufmservices.net/plugins/menuedit.zip --activate

if [ "$woo" == "y" ]
then
echo "Installing wooCommerce..."
wp plugin install woocommerce --activate
fi

# install the core theme
echo "Installing Horizon theme..."
cd wp-content/themes/
git clone https://ufmedia:fa4f3d70c1579dd2498924e5e0924875d536dec8@github.com/ufmedia/horizon-4.0.git
#git clone https://ufmedia:fa4f3d70c1579dd2498924e5e0924875d536dec8@github.com/ufmedia/horizon-child.git
mv horizon-4.0/ horizon
cd horizon
rm -rf nbproject
rm -rf .git
rm -rf .gitattributes
rm -rf .gitignore

cd ..

wp theme activate horizon

echo "Removing default themes..."
wp theme delete twentyseventeen
wp theme delete twentysixteen
wp theme delete twentynineteen
wp theme delete twentytwenty
wp theme delete twentytwentyone

echo "Configuring system..."
# discourage search engines
wp option update blog_public 0
# show only 6 posts on an archive page
wp option update posts_per_page 6

# delete sample page, and create homepage
echo "Setting up homepage..."
wp post delete $(wp post list --post_type=page --posts_per_page=1 --post_status=publish --pagename="sample-page" --field=ID --format=ids)
wp post create horizon/includes/tools/dummy --post_type=page --post_title=Home --post_status=publish --post_author=$(wp user get $wpuser --field=ID --format=ids)

# set homepage as front page
wp option update show_on_front 'page'

# set homepage to be the new page
wp option update page_on_front $(wp post list --post_type=page --post_status=publish --posts_per_page=1 --pagename=home --field=ID --format=ids)

#Create Main Menu
echo "Creating Main Menu..."
wp menu create "Main Menu"

echo "Creating Pages..."
# create all of the pages
export IFS=","
m=5
for page in $allpages; do
        wp post create horizon/includes/tools/dummy --post_type=page --post_status=publish --post_author=$(wp user get $wpuser --field=ID --format=ids) --post_title="$(echo $page | sed -e 's/^ *//' -e 's/ *$//')"
        wp menu item add-post main-menu $m 
        m=$((m+1))
done

echo "Creating dummy posts..."
#Create dummy posts
curl -N http://loripsum.net/api/5 | wp post generate --post_content --count=10

echo "Creating CPTs with dummy content..."
#create post types
export IFS=","
y=5
for post in $allCPTs; do
        wp scaffold post-type $post --label=$post --theme=horizon
        sed -i "/\[CPTs\]/a include_once('post-types/$post.php');" horizon/functions.php
        curl -N http://loripsum.net/api/5 | wp post generate --post_content --post_type=$post --count=10
        cp horizon/includes/templates/loops/posts.php horizon/includes/templates/loops/$post.php
        sed -i -e "s/'post'/'$post'/g" horizon/includes/templates/loops/$post.php
        cp horizon/single.php horizon/single-$post.php
        sed -i "/\[CPTs\]/r horizon/includes/tools/featBlock" horizon/front-page.php
        sed -i -e "s/'CPT'/$post/g" horizon/front-page.php
        y=$((y+1))
done

echo "Tidying up..."
# set pretty urls
wp rewrite flush
wp rewrite structure '/%postname%/'


echo "================================================================="
echo "Wordpress Installation is complete!"
echo "================================================================="
echo "Admin Username: $wpuser"
echo "Admin Password: jt00"
echo "Site location: http://$rooturl/$currentdirectory"
echo "================================================================="
echo "Starting Gulp setup"
echo "================================================================="

cd horizon/horizon-gulp

npm install --save-dev
#npm install gulp --save-dev
#npm install gulp-cssnano gulp-uglify gulp-rename gulp-livereload gulp-sass gulp-plumber del --save-dev

echo "Starting default gulp task..."
gulp watch

fi

